### ISSUE TITLE
operaciones basicas

### ISSUE THREAD

**Issue by lucero012** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-lucero012#2]
[operaciones basicas. lucero.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-lucero012/files/7207358/operaciones.basicas.lucero.pdf)

**Comment by lourdeshernandez2003** [comment]
tomando en  cuanta la rubrica, los puntos que tiene que llevar la practica no cumple todo todos los puntos,no le agrego referencias, no le agrego resultados,tampoco agrego una descripción por esos motivos le asigno el 17%.

**Comment by josealfredo79** [comment]
Revisado y bien hecho...
